# Generated by Django 2.1.1 on 2018-09-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=128, verbose_name='Nazwa apartamentu')),
                ('description', models.TextField(verbose_name='Opis apartamentu')),
                ('address_city', models.SmallIntegerField(choices=[(1, 'Warszawa'), (2, 'Kraków'), (3, 'Poznań'), (4, 'Wrocław')])),
                ('address_code', models.CharField(help_text='00-000', max_length=6, verbose_name='kod')),
                ('address_str', models.CharField(max_length=128, verbose_name='Ulica i nr')),
                ('address_no', models.CharField(max_length=16, null=True, verbose_name='nr lokalu')),
                ('area', models.SmallIntegerField(verbose_name='powierzchnia')),
                ('floor', models.SmallIntegerField(verbose_name='piętro')),
                ('no_of_rooms', models.SmallIntegerField(verbose_name='liczba pokoi')),
                ('no_of_guests', models.SmallIntegerField(verbose_name='liczba osób')),
                ('no_of_beds', models.SmallIntegerField(verbose_name='liczba łóżek')),
                ('own_parking', models.BooleanField(default=False, verbose_name='miejsce parkingowe')),
                ('facilities', models.SmallIntegerField(choices=[(1, 'wifi'), (2, 'TV kablowa'), (3, 'TV'), (4, 'winda'), (4, 'wyposażona kuchnia'), (5, 'zestaw do parzenia kawy'), (6, 'żelazko'), (7, 'suszarka'), (8, 'pralka'), (9, 'taras/balkon'), (10, 'klimatyzacja'), (11, 'prysznic'), (12, 'wanna'), (13, 'piekarnik'), (14, 'mikrofalówka'), (15, 'kominek')], verbose_name='Udogodnienia/Wyposażenie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit', models.SmallIntegerField(choices=[(1, '100'), (2, '200'), (3, '300'), (4, '400'), (5, '500'), (6, '600')], verbose_name='zwrotna kaucja')),
            ],
            options={
                'ordering': ['address_city', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='dodatkowa opłata')),
                ('fee_value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('company_name', models.CharField(max_length=128, null=True, verbose_name='Nazwa firmy')),
                ('if_vat', models.BooleanField(default=True, verbose_name='Czy płatnik VAT')),
                ('vat_number', models.CharField(max_length=10, null=True, verbose_name='NIP')),
                ('address_city', models.CharField(max_length=128, verbose_name='Miasto')),
                ('address_code', models.CharField(help_text='00-000', max_length=6, verbose_name='kod')),
                ('address_str', models.CharField(max_length=128, verbose_name='Ulica i nr')),
                ('address_no', models.CharField(max_length=16, null=True, verbose_name='nr lokalu')),
                ('tel_no', models.CharField(max_length=32, null=True, verbose_name='Nr telefonu')),
                ('e_mail', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje')),
            ],
            options={
                'verbose_name': 'Właścicel',
                'verbose_name_plural': 'Właściciele',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(max_length=128, upload_to='photos/', verbose_name='zdjęcie')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprtrent.User'),
        ),
        migrations.AddField(
            model_name='appartment',
            name='fees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprtrent.Fee'),
        ),
        migrations.AddField(
            model_name='appartment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprtrent.Owner'),
        ),
    ]
