# Generated by Django 2.1.1 on 2018-10-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('checkin_date', 'checkout_date', 'appartment')},
        ),
    ]
