# Generated by Django 2.1.1 on 2018-10-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0002_auto_20181002_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(max_length=128, upload_to='photos/', verbose_name='zdjęcie apartamentu')),
            ],
        ),
        migrations.AddField(
            model_name='appartment',
            name='best_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='appartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprtrent.Appartment'),
        ),
    ]
