# Generated by Django 2.1.1 on 2018-10-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0004_auto_20181002_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='best_app',
            field=models.BooleanField(default=True, help_text='czy apartament ma być pokazywany na stronie głównej', verbose_name='wyróżniony'),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprtrent.Owner', verbose_name='właściciel'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nazwa firmy'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nazwisko'),
        ),
    ]
