# Generated by Django 2.1.1 on 2018-10-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0006_auto_20181002_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Udogodnienia/Wyposażenie')),
            ],
        ),
        migrations.AlterField(
            model_name='appartment',
            name='facilities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprtrent.Facility', verbose_name='Udogodnienia/Wyposażenie'),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena'),
        ),
    ]
