# Generated by Django 2.1.1 on 2018-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0007_auto_20181002_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='fee_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='appartment',
            name='facilities',
        ),
        migrations.AddField(
            model_name='appartment',
            name='facilities',
            field=models.ManyToManyField(to='apprtrent.Facility', verbose_name='udogodnienia/wyposażenie'),
        ),
        migrations.RemoveField(
            model_name='appartment',
            name='fees',
        ),
        migrations.AddField(
            model_name='appartment',
            name='fees',
            field=models.ManyToManyField(to='apprtrent.Fee', verbose_name='dodatkowe opłąty'),
        ),
    ]
