# Generated by Django 2.1.1 on 2018-10-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0008_auto_20181003_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(max_length=128, upload_to='app_directory_path', verbose_name='zdjęcie apartamentu'),
        ),
    ]
