# Generated by Django 2.1.1 on 2018-10-03 16:55

import apprtrent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0009_auto_20181003_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appartment',
            options={'ordering': ['address_city', 'price'], 'permissions': (('new_appartment', 'Can add new appartment'),)},
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(max_length=128, upload_to=apprtrent.models.app_directory_path, verbose_name='zdjęcie apartamentu'),
        ),
    ]
