# Generated by Django 2.1.1 on 2018-10-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0010_auto_20181003_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='own_parking',
        ),
    ]
