# Generated by Django 2.1.1 on 2018-10-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0011_remove_appartment_own_parking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appartment',
            options={'ordering': ['address_city', 'app_name'], 'permissions': (('new_appartment', 'Can add new appartment'),)},
        ),
        migrations.RemoveField(
            model_name='appartment',
            name='price',
        ),
        migrations.AddField(
            model_name='appartment',
            name='coders_monthly_price',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=6, verbose_name='Cena za mc dla kursantów Coderslab'),
        ),
        migrations.AddField(
            model_name='appartment',
            name='day_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='Cena za dzień'),
        ),
    ]
