# Generated by Django 2.1.1 on 2018-10-04 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0012_auto_20181004_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='deposit',
            field=models.SmallIntegerField(default=0, verbose_name='zwrotna kaucja'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Rezerwacja od dnia'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateField(verbose_name='Rezerwacja do dnia'),
        ),
    ]
