# Generated by Django 2.1.1 on 2018-10-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0013_auto_20181004_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='coders_monthly_price',
        ),
        migrations.AddField(
            model_name='appartment',
            name='coders_weekly_price',
            field=models.DecimalField(decimal_places=2, default=400.0, max_digits=6, verbose_name='Cena tygodniowego wynajmu dla kursantów Coderslab'),
        ),
    ]
