# Generated by Django 2.1.1 on 2018-10-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0014_auto_20181004_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tel_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nr telefonu')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AlterField(
            model_name='appartment',
            name='address_no',
            field=models.CharField(blank=True, default=None, max_length=16, verbose_name='nr lokalu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appartment',
            name='coders_weekly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=400.0, max_digits=6, null=True, verbose_name='Cena tygodniowego wynajmu dla kursantów Coderslab'),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis apartamentu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='address_no',
            field=models.CharField(blank=True, default=0, max_length=16, verbose_name='nr lokalu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Dodatkowe informacje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Nazwa firmy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='e_mail',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Imię'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Nazwisko'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='tel_no',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Nr telefonu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='NIP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apprtrent.Tenant'),
            preserve_default=False,
        ),
    ]
