# Generated by Django 2.1.1 on 2018-10-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0015_auto_20181004_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tenant',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appartment',
            name='fees',
            field=models.ManyToManyField(to='apprtrent.Fee', verbose_name='dodatkowe opłaty'),
        ),
    ]
