# Generated by Django 2.1.1 on 2018-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0016_auto_20181004_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.AddField(
            model_name='appartment',
            name='distance',
            field=models.SmallIntegerField(choices=[(1, 'bardzo blisko'), (2, 'blisko'), (3, 'dojazd komunikacją miejską'), (4, 'dłuższy dojazd komunikacją miejską')], default=1, verbose_name='odległość od Coderslab'),
            preserve_default=False,
        ),
    ]
