# Generated by Django 2.1.1 on 2018-10-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0017_auto_20181004_1805'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
