# Generated by Django 2.1.1 on 2018-10-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0018_auto_20181004_1919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('checkin_date', 'checkout_date', 'appartment')},
        ),
    ]
