# Generated by Django 2.1.1 on 2018-11-18 09:59

import apprtrent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0020_auto_20181007_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appartment',
            options={'ordering': ['address_city', 'app_name'], 'permissions': (('new_appartment', 'Can add new appartment'), ('modify_appartment', 'Can change appartment'))},
        ),
        migrations.AlterField(
            model_name='appartment',
            name='distance',
            field=models.SmallIntegerField(choices=[(1, 'w Centrum'), (2, 'blisko'), (3, 'szybki dojazd komunikacją miejską'), (4, 'daleko od Centrum')], verbose_name='odległość od Centrum'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(blank=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(max_length=128, upload_to=apprtrent.models.app_directory_path),
        ),
    ]
