# Generated by Django 2.1.3 on 2018-11-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprtrent', '0021_auto_20181118_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='coders_weekly_price',
        ),
        migrations.AddField(
            model_name='appartment',
            name='special_weekly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=400.0, max_digits=6, null=True, verbose_name='Cena specjalna za tydzień wynajmu'),
        ),
    ]
